// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Account
{
    public string email { get; set; }

    public string user_name { get; set; }

    public string password { get; set; }
}