// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Cart
{
    public int IDUser { get; set; }

    public int IDProduct { get; set; }

    public int? NumberOfProduct { get; set; }

    public virtual Inventory IDProductNavigation { get; set; }

    public virtual User IDUserNavigation { get; set; }
}