// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Cart
{
    public int IdCart { get; set; }

    public int? IdUser { get; set; }

    public int? IdShop { get; set; }

    public int? IdProduct { get; set; }

    public int? Number { get; set; }
}