// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Cart
{
    public int ID_Cart { get; set; }

    public int? ID_User { get; set; }

    public int? ID_Shop { get; set; }

    public int? ID_Product { get; set; }

    public int? Number { get; set; }
}