// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Image_link
{
    public int Id { get; set; }

    public string Image_link1 { get; set; }
}