// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Inventory
{
    public int IDProduct { get; set; }

    public int IDShop { get; set; }

    public string Name { get; set; }

    public float? Price { get; set; }

    public float? Discount { get; set; }

    public string Newness { get; set; }

    public string Type { get; set; }

    public float? Rating { get; set; }

    public int? Number { get; set; }

    public int? NumberSold { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual Shop IDShopNavigation { get; set; }

    public virtual ICollection<ImageLink> ImageLinks { get; set; } = new List<ImageLink>();
}