// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Inventory
{
    public int IDProduct { get; set; }

    public int IDShop { get; set; }

    public string Name { get; set; }

    public float? OriginalPrice { get; set; }

    public float? CurrentPrice { get; set; }

    public float? Save { get; set; }

    public float? Newness { get; set; }

    public string Type { get; set; }

    public int? NumberInput { get; set; }

    public int? NumberLeft { get; set; }

    public DateTime? BoughtTime { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual Shop IDShopNavigation { get; set; }

    public virtual ICollection<ImageLink> ImageLinks { get; set; } = new List<ImageLink>();
}