// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Kho
{
    public int Id_sanpham { get; set; }

    public int Id_shop { get; set; }

    public string Ten { get; set; }

    public float? Gia { get; set; }

    public float? Discount { get; set; }

    public string DoMoi { get; set; }

    public string Type { get; set; }

    public float? Rate { get; set; }

    public int? Number { get; set; }

    public string NumberSold { get; set; }
}