// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Kho
{
    public Kho()
    {
    }

    public Kho(int idSanpham, int idShop, string ten, float? gia, float? discount, string doMoi, string type, float? rate, int? number, int? numberSold, Shop idShopNavigation)
    {
        IdSanpham = idSanpham;
        IdShop = idShop;
        Ten = ten;
        Gia = gia;
        Discount = discount;
        DoMoi = doMoi;
        Type = type;
        Rate = rate;
        Number = number;
        NumberSold = numberSold;
        IdShopNavigation = idShopNavigation;
    }

    public int IdSanpham { get; set; }

    public int IdShop { get; set; }

    public string Ten { get; set; }

    public float? Gia { get; set; }

    public float? Discount { get; set; }

    public string DoMoi { get; set; }

    public string Type { get; set; }

    public float? Rate { get; set; }

    public int? Number { get; set; }

    public int? NumberSold { get; set; }

    public virtual Shop IdShopNavigation { get; set; }
}