// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Owner
{
    public int ID { get; set; }

    public int ID_Shop { get; set; }

    public string CMND { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Sex { get; set; }

    public DateTime? DoB { get; set; }

    public string Avatar_Source { get; set; }

    public string Phone_Number { get; set; }

    public string Email { get; set; }
}