// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Product
{
    public int ID_Product { get; set; }

    public float? Name_Product { get; set; }

    public string Avatar_Product { get; set; }

    public float? Name_Producer { get; set; }
}