// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Shop
{
    public int IDShop { get; set; }

    public string NameShop { get; set; }

    public string Address { get; set; }

    public string ShopAvatar { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public virtual Account IDShopNavigation { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();
}