// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class Shop
{
    public int ID_Shop { get; set; }

    public string Name_Shop { get; set; }

    public string Address { get; set; }

    public string Shop_Avatar { get; set; }

    public string Phone_Number { get; set; }

    public string Email { get; set; }
}