// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WPF_Market.Models;

public partial class TraoDoiMuaBanContext : DbContext
{
    public TraoDoiMuaBanContext(DbContextOptions<TraoDoiMuaBanContext> options)
        : base(options)
    {
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(Properties.Settings.Default.TraoDoiMuaBan);

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Image_link> Image_links { get; set; }

    public virtual DbSet<Iventory> Iventories { get; set; }

    public virtual DbSet<Kho> Khos { get; set; }

    public virtual DbSet<Owner> Owners { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Shop> Shops { get; set; }

    public virtual DbSet<Table> Tables { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.user_name);

            entity.ToTable("Account");

            entity.Property(e => e.user_name).HasMaxLength(50);
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.password).HasMaxLength(50);
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.ID_Cart).HasName("PK__Cart__72140ECF58F14122");

            entity.ToTable("Cart");

            entity.Property(e => e.ID_Cart).ValueGeneratedNever();
        });

        modelBuilder.Entity<Image_link>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Image_li__3214EC07F5B1FC79");

            entity.ToTable("Image_link");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Image_link1).HasColumnName("Image_link");
        });

        modelBuilder.Entity<Iventory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Iventory__3214EC075DDE3D32");

            entity.ToTable("Iventory");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Kho>(entity =>
        {
            entity.HasKey(e => e.Id_sanpham).HasName("PK__Kho__0BC662851DC71AC6");

            entity.ToTable("Kho");

            entity.Property(e => e.Id_sanpham).ValueGeneratedNever();
            entity.Property(e => e.DoMoi)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.NumberSold)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Type).HasMaxLength(50);
        });

        modelBuilder.Entity<Owner>(entity =>
        {
            entity.HasKey(e => new { e.ID, e.ID_Shop }).HasName("PK__Owner__3CA78C9ED5DC9FA2");

            entity.ToTable("Owner");

            entity.Property(e => e.Address).HasMaxLength(50);
            entity.Property(e => e.CMND).HasMaxLength(50);
            entity.Property(e => e.DoB).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Phone_Number).HasMaxLength(50);
            entity.Property(e => e.Sex).HasMaxLength(50);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ID_Product).HasName("PK__Product__522DE496D03E9FE4");

            entity.ToTable("Product");

            entity.Property(e => e.ID_Product).ValueGeneratedNever();
        });

        modelBuilder.Entity<Shop>(entity =>
        {
            entity.HasKey(e => e.ID_Shop).HasName("PK__tmp_ms_x__EB360B91AD8C4FCF");

            entity.ToTable("Shop");

            entity.Property(e => e.ID_Shop).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(50);
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.Name_Shop).HasMaxLength(50);
            entity.Property(e => e.Phone_Number).HasMaxLength(50);
        });

        modelBuilder.Entity<Table>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Table__3214EC07855BFBBF");

            entity.ToTable("Table");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC07F5BFA233");

            entity.ToTable("User");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(50);
            entity.Property(e => e.CMND).HasMaxLength(50);
            entity.Property(e => e.DoB).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.Id_fav_product)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Phone_Number).HasMaxLength(50);
            entity.Property(e => e.Sex).HasMaxLength(50);
            entity.Property(e => e.id_fav_shop)
                .HasMaxLength(10)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}