// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class User
{
    public int Id { get; set; }

    public string Cmnd { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Sex { get; set; }

    public DateTime? DoB { get; set; }

    public string AvatarSource { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public float? Budget { get; set; }

    public int? IdShop { get; set; }

    public string IdFavProduct { get; set; }

    public string IdFavShop { get; set; }
}