// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class User
{
    public int ID { get; set; }

    public string IdentityNum { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Sex { get; set; }

    public DateTime? DoB { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public float? Budget { get; set; }

    public int? IDShop { get; set; }

    public string IDFavProduct { get; set; }

    public string IDFavShop { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual Account IDNavigation { get; set; }
}