// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Market.Models;

public partial class User
{
    public int Id { get; set; }

    public string IdentityNum { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Sex { get; set; }

    public DateTime? DoB { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public float? Budget { get; set; }

    public int? Idshop { get; set; }

    public string IdfavProduct { get; set; }

    public string IdfavShop { get; set; }

    public virtual Account IdNavigation { get; set; }
}